language: python
dist: bionic
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS users;'
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=services -m unittest discover -s tests/
  - coverage report
notifications:
  email: false
