language: python
dist: bionic
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_users;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_cards;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_doctors;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_appoints;'
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=services -m unittest discover -s tests/
  - coverage report
notifications:
  email: false
