"""doctor table

Revision ID: 1c05cd9a7da7
Revises: 71fa0e161065
Create Date: 2019-11-20 16:07:49.505278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c05cd9a7da7'
down_revision = '71fa0e161065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'id_card',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('doctors', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.alter_column('doctors', 'id_card',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
